In [1]:
import pandas as pd

In [2]:
file_path = "../Data/Global Superstore Data.xlsx"

In [3]:
excel_file = pd.ExcelFile(file_path)

In [4]:
excel_file.sheet_names

['Orders', 'Returns', 'People']

In [5]:
orders = pd.read_excel(file_path, sheet_name="Orders")

In [6]:
returns = pd.read_excel(file_path, sheet_name="Returns")

In [7]:
people = pd.read_excel(file_path, sheet_name="People")

In [8]:
orders.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,24599,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NaN,Herat,...,FUR-BO-4861,"Ikea Library with Doors, Mobile",Bookcases,Furniture,731.82,2,0.0,102.42,39.66,Medium
1,29465,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NaN,Herat,...,OFF-SU-2988,"Acme Scissors, Easy Grip",Supplies,Office Supplies,243.54,9,0.0,104.49,18.72,Medium
2,24598,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NaN,Herat,...,TEC-MA-4211,"Epson Receipt Printer, White",Machines,Technology,346.32,3,0.0,13.77,14.10,Medium
3,24597,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NaN,Herat,...,FUR-FU-5726,"Rubbermaid Door Stop, Erganomic",Furnishings,Furniture,169.68,4,0.0,79.68,11.01,Medium
4,29464,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NaN,Herat,...,OFF-EN-3664,"Cameo Interoffice Envelope, with clear poly wi...",Envelopes,Office Supplies,203.88,4,0.0,24.36,5.72,Medium

In [9]:
returns.head()

  Returned                Order ID         Region
0      Yes  IN-2017-CA120551-42816  Southern Asia
1      Yes  IN-2017-AA103751-42926  Southern Asia
2      Yes  IN-2017-TS212051-42904  Southern Asia
3      Yes   AG-2014-RO97803-41695   North Africa
4      Yes   AG-2015-LC70503-42265   North Africa

In [10]:
people.head()

              Person           Region
0  Marilène Rousseau        Caribbean
1   Andile Ihejirika   Central Africa
2  Nicodemo Bautista  Central America
3     Cansu Peynirci     Central Asia
4         Lon Bonher       Central US

In [11]:
orders.shape

(51290, 24)

In [12]:
returns.shape

(2033, 3)

In [13]:
people.shape

(24, 2)

In [14]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  datetime64[ns]
 3   Ship Date       51290 non-null  datetime64[ns]
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   Postal Code     9994 non-null   float64
 9   City            51290 non-null  object
 10  State           51290 non-null  object
 11  Country         51290 non-null  object
 12  Region          51290 non-null  object
 13  Market          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Product Name    51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Category        51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(2), object(15)
memory usage: 9.4+ MB

In [15]:
returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2033 entries, 0 to 2032
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Returned  2033 non-null   object
 1   Order ID  2033 non-null   object
 2   Region    2033 non-null   object
dtypes: object(3)
memory usage: 47.8+ KB

In [16]:
people.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Person  24 non-null     object
 1   Region  24 non-null     object
dtypes: object(2)
memory usage: 516.0+ bytes

In [17]:
orders.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Postal Code       41296
City                  0
State                 0
Country               0
Region                0
Market                0
Product ID            0
Product Name          0
Sub-Category          0
Category              0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [18]:
returns.isnull().sum()

Returned    0
Order ID    0
Region      0
dtype: int64

In [19]:
people.isnull().sum()

Person    0
Region    0
dtype: int64

In [20]:
orders.to_csv("../Data/orders.csv", index=False)

returns.to_csv("../Data/returns.csv", index=False)

people.to_csv("../Data/people.csv", index=False)